# Generated by Django 5.2.4 on 2025-07-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_commande_lignecommande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='moyen_paiement',
            field=models.CharField(choices=[('carte', 'Carte bancaire'), ('paypal', 'Compte PayPal')], default='carte', max_length=20),
        ),
    ]
