# Generated by Django 5.2.4 on 2025-07-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0003_commande_moyen_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='actif',
            field=models.BooleanField(default=True),
        ),
    ]
