# Generated by Django 5.2.4 on 2025-07-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0004_produit_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='seuil_alerte',
            field=models.PositiveIntegerField(default=0, verbose_name='Seuil d’alerte stock'),
        ),
    ]
